# Generated by Django 2.1.3 on 2018-12-04 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nums', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='model',
            new_name='model1',
        ),
    ]
