# Generated by Django 2.1.3 on 2018-12-04 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nums', '0002_auto_20181204_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model1',
            name='time_estimated',
        ),
    ]
