# Generated by Django 2.1.3 on 2018-12-04 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nums', '0003_remove_model1_time_estimated'),
    ]

    operations = [
        migrations.CreateModel(
            name='model2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_estimated', models.DateTimeField(auto_now_add=True)),
                ('accuracy', models.FloatField(default=0)),
            ],
        ),
    ]
