# Generated by Django 2.1.3 on 2018-12-04 19:18

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import nums.models


class Migration(migrations.Migration):

    dependencies = [
        ('nums', '0004_model2'),
    ]

    operations = [
        migrations.AddField(
            model_name='model1',
            name='name',
            field=models.CharField(default='test', max_length=200),
        ),
        migrations.AddField(
            model_name='model2',
            name='activations',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=nums.models.default_activations),
        ),
        migrations.AddField(
            model_name='model2',
            name='default',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='model2',
            name='dropout_prob',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='model2',
            name='name',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='model2',
            name='number_of_layers',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='model2',
            name='unit_numbers_in_layers',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=nums.models.default_units),
        ),
    ]
