# Generated by Django 2.1.3 on 2018-12-05 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nums', '0005_auto_20181204_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='model2',
            name='model_path',
            field=models.TextField(default='/var/www/models/'),
        ),
    ]
